# Generated by Django 4.1.5 on 2023-01-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
