# Generated by Django 4.1.5 on 2023-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_teachers_teacher_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='../restframework/img')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
    ]
