# Generated by Django 4.1.5 on 2023-01-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Media',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Medias'},
        ),
    ]
