# Generated by Django 4.1.5 on 2023-01-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_file_media_alter_media_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('familyName', models.CharField(max_length=20)),
                ('givenName', models.CharField(max_length=20)),
                ('googleId', models.IntegerField(blank=True, max_length=100, null=True)),
                ('imageUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
