# Generated by Django 4.1.5 on 2023-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='googleId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
